---
title: "Description of the FLjjm package"
author:
  - "Name SURNAME"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
bibliography: bibliography.bib
tags: FLPKG FLR
license: Creative Commons Attribution-ShareAlike 4.0 International
---

```{r, pkgs, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(collapse = T, comment = "#>")
library(FLCore)
```

# Using the FLjjm package

# Loading *jjms* outputs

```
       readFLBjjm           FLomBF
model ------------- FLBiol ---------- OM (FLomBF)
       |-- jjmR::readJJM    |-- biol
       `-- buildFLBjjm      |-- fisheries
                            `-- refpts 
       `----------- buildFLomFB ------------|
```

# Running *jjms*

```
        cjm.oem            buildjjm              writeJJM          exejjms
FLomBF --------- FLStock  ---------- jjm.output ---------- mod.dat -------- model
       |         FLIndices                                 mod.ctl
       |-- buildjjmdat
       `-- buildjjmctl
                                      `-------------- runjjms -----------------|
                  `---------------------- jjms --------------------------------|
```

# jjms.sa

```
jjms
└── runjjms
    └── exejjms
        │── calljjms
        └── packjjmsrun
```


# Observation Error Model (oem)

### Indices of abundance to generate in MP:

- `Chile_AcousN`
- `Chile_CPUE`
- `Peru_CPUE`
- `Offshore_CPUE`

## Example / Workflow 1

## Example / Workflow 2

# Reference

## `buildjjmdata`

## `buildFLIsjjm`

- Creates and object of class `FLIndices` containing the indices of abundance used in the `jjms` model runs.

# FLIndex

# More information

## Software Versions

* `r version$version.string`
* FLCore: `r packageVersion('FLCore')`
* FLjjm: `r packageVersion('FLjjm')`
* jjmR: `r packageVersion('jjmR')`
* **Compiled**: `r date()`
* **Git Hash**: `r system("git log --pretty=format:'%h' -n 1", intern=TRUE)`

## Author information

* **Name SURNAME**. Affiliation. Address, Locality (RE) Country.
* **Name SURNAME**. Affiliation. Address, Locality (RE) Country.
* **Name SURNAME**. Affiliation. Address, Locality (RE) Country.

# References
